name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cd auth && npm install && npm run test:ci
